version: "2"

linters:

  default: all

  disable:
    - wsl
    - wsl_v5
    - nlreturn
    - revive
    - nonamedreturns
    - wrapcheck
    - mnd
    - varnamelen
    - gosec
    - errorlint
    - errcheck
    - cyclop
    - funlen
    - whitespace

  settings:

    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/tetratelabs/wazero/api
            - github.com/tetratelabs/wazero
            - github.com/takanoriyanagitani/go-bytes2hex4wasm
          deny:
            - pkg: unsafe

    nolintlint:
      require-specific: true
      require-explanation: true
      allow-unused: false
      allow-no-explanation:
        - gochecknoglobals

    govet:
      enable-all: true
      disable:
      - fieldalignment

    staticcheck:
      checks:
      - all
      - -QF1011
      - -QF1008
      - -ST1017
      - -ST1023
      - -ST1000
